scalar JSON

type User {
  id: ID!
  username: String!
  name: String
  email: String
  admin: Boolean!
}

type Exam {
  id: ID!
  name: String!
  code: String
  sector: String!
  credits: Int!
  tags: [String!]
  notes: String
}

type Degree {
  id: ID!
  name: String!
  academic_year: Int!
  years: Int!
  enabled: Boolean!
  sharing_mode: String!
  groups: JSON
  default_group: String
  approval_confirmation: Boolean!
  rejection_confirmation: Boolean!
  submission_confirmation: Boolean!
  approval_message: String
  rejection_message: String
  submission_message: String
  free_choice_message: String
}

type Curriculum {
  id: ID!
  name: String!
  notes: String
  degree: Degree
}

type Proposal {
  id: ID!
  user: User
  curriculum: Curriculum
  degree: Degree
  state: String!
  date_modified: String
  date_submitted: String
  date_managed: String
}

type Query {
  users: [User!]!
  user(id: ID!): User
  exams: [Exam!]!
  examsByIds(ids: [ID!]!): [Exam!]!
  exam(id: ID!): Exam
  degrees: [Degree!]!
  degree(id: ID!): Degree
  curricula: [Curriculum!]!
  curriculum(id: ID!): Curriculum
  proposals: [Proposal!]!
  proposal(id: ID!): Proposal
}

type Mutation {
  createUser(username: String!, password: String!, admin: Boolean): User
  updateDegree(id: ID!, input: DegreeInput!): Degree
  deleteDegree(id: ID!): Boolean
}

input DegreeInput {
  name: String!
  academic_year: Int!
  years: Int!
  enabled: Boolean!
  sharing_mode: String!
  groups: JSON
  default_group: String
  approval_confirmation: Boolean!
  rejection_confirmation: Boolean!
  submission_confirmation: Boolean!
  approval_message: String
  rejection_message: String
  submission_message: String
  free_choice_message: String
}