# This is essentially the same file, but it mounts the source files
# for CAPS into the image directly, so that develpoment can be carried
# out without rebuilding the image. 
version: '2.3'

services:
  caps:
    build: ..
    container_name: caps
    ports:
      - 8765:80
    volumes:
      # This is set anyway, in case it does not exists a folder
      # is created, which is harmless. Otherwise, this should be
      # a file with a private RSA key for SSH authentication
      - "./id_rsa:/app/id_rsa:ro"
      - "../app/src:/app/src:ro"
      - "../app/templates:/app/templates:ro"
      - "../app/webroot:/app/webroot:ro"
      - "../app/config/Migrations:/app/config/Migrations"
      - "./logs:/app/logs"
    env_file:
      - caps.env
    environment:
      # Enable DebugKit on the development server
      DEBUG: "true"
      CAPS_DB_DRIVER: "mysql"
      CAPS_DB_HOST: "caps-db"
      CAPS_DB_USERNAME: "caps"
      CAPS_DB_PASSWORD: "secret"
      CAPS_DB_DATABASE: "caps"
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN # For fuse
      
  caps-db:
    image: mysql:8
    container_name: caps-db
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes: 
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_USER=caps
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=caps
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE to avoid mbind messages in the log. 
