version: '2.3'

services:
  caps:
    image: getcaps/caps:master
    container_name: caps
    ports:
      - 80:80
    volumes:
      # This is set anyway, in case it does not exists a folder
      # is created, which is harmless. Otherwise, this should be
      # a file with a private RSA key for SSH authentication
      - "./id_rsa:/app/id_rsa"
    env_file:
      - caps.env
    environment:
      DEBUG: "false"
      
  caps-db:
    image: mysql:8
    container_name: caps-db
    volumes: 
      - ./database:/var/lib/mysql
    env_file:
      - caps.env    
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE to avoid mbind messages in the logs
