# This is essentially the same file, but it mounts the source files
# for CAPS into the image directly, so that develpoment can be carried
# out without rebuilding the image. 
version: '2.3'

services:
  caps:
    image: ghcr.io/unipisa/caps:develop
    container_name: caps
    ports:
      - 8765:80
    volumes:
      # This is set anyway, in case it does not exists a folder
      # is created, which is harmless. Otherwise, this should be
      # a file with a private RSA key for SSH authentication
      - "../backend/src:/backend/src:ro"
      - "../backend/templates:/backend/templates:ro"
      - "../backend/webroot:/backend/webroot:ro"
      - "../backend/config/Migrations:/backend/config/Migrations"
      - "../backend/config/routes.php:/backend/config/routes.php"
      - "./logs:/backend/logs"
    env_file:
      - caps.env
    environment:
      # Enable DebugKit on the development server
      DEBUG: "true"
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN # For fuse
      
  caps-db:
    image: mysql:8
    container_name: caps-db
    env_file:
      - caps.env
    # command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./database:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE to avoid mbind messages in the log. 
