#!/bin/bash
#
# Script used to update CAPS installed as git cloned repository
# in CAPSDIRECTORY. Run this script as a user which has permission
# to do a git pull.

set -e

# We use webroot directory as a sign of having a CakePHP installation there
for CAPSDIRECTORY in $(find /var/www -name bootstrap_cli.php -exec dirname {} \;); do
  cd ${CAPSDIRECTORY}/..
  CAPSDIRECTORY=$(pwd)
  echo "$(date): Aggiornamento di ${CAPSDIRECTORY}"

  current_HEAD=$(git rev-parse HEAD)
  git pull > /dev/null
  new_HEAD=$(git rev-parse HEAD)

  if [ "${new_HEAD}" != "${current_HEAD}" ]; then
    echo "HEAD: ${current_HEAD} -> ${new_HEAD}"

    # Install all the software required
    composer install -n

    # Perform DB migrations, if needed
    bin/cake migrations migrate

    # Clear cache -- this helps in case new models are
    # introduced, or if new fields are added
    bin/cake cache clear_all
  fi
done
