name: tests

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JS tests
        run: |
          cd frontend/
          npm ci
          npm run test
          npm run deploy
          npm run deploy:dev
      - name: PHP tests
        run: |
          cd backend/
          php7.4 -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php7.4 composer-setup.php
          php7.4 -r "unlink('composer-setup.php');"
          sudo apt-get -y install php-mbstring php-intl php-xml php-sqlite3 php-mysql php-zip php-ldap php-gd
          php7.4 composer.phar -n install
          bin/cake migrations migrate
          php7.4 vendor/bin/phpunit --debug
      - name: Pull previous Docker image
        run: |
          docker pull getcaps/caps:develop
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: registry.cs.dm.unipi.it/getcaps/caps
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=semver,pattern={{version}}
      - name: Login to Docker Registry
        uses: docker/login-action@v1 
        if: ${{ github.event_name != 'pull_request' }}
        with:
          username: ${{ secrets.REGISTRY_CS_USERNAME }}
          password: ${{ secrets.REGISTRY_CS_PASSWORD }}
          registry: registry.cs.dm.unipi.it
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          push: true
          cache-from: type=registry,ref=registry.cs.dm.unipi.it/getcaps/caps:develop
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Trigger update on Watchtower
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          curl -H "Authorization: Bearer ${{ secrets.WATCHTOWER_CAPS_SECRET }}" https://watchtower.docker.cs.dm.unipi.it/v1/update
